
# (PART) Remote computing {-} 

# Introduction

Sometimes, you'll come across data sets that are too large to work with on your local computer. If you're at Stanford, you can use Stanford's shared computing environment, [FarmShare 2](https://srcc.stanford.edu/farmshare2), to work with large data files. 

FarmShare 2 has three different classes of servers: _rice_, _wheat_, and _oat_ (named after crops that grow on farms). We'll only talk about the rice and wheat servers. In order to understand the different environments, you'll need to understand the distinction between _interactive jobs_ and _batch jobs_. 

Interactive jobs include things like running Rscripts, working in RStudio, and moving files. With interactive jobs, you log into the server and then carry out tasks similarly to how you would on your local computer. 

To run a batch job, you write a script and then submit that script to the server. You don't interact with the server besides sending it the script. FarmShare 2 uses [Slurm](https://slurm.schedmd.com/), so to submit a batch job, you'll need to write a Slurm script. We'll explain how to do this later on.

The rice machines can carry out interactive jobs, and the wheat machines can carry out both interactive and batch jobs. We'll show you how to log into rice to work in RStudio and run Rscripts, and then how to submit batch jobs to wheat. 